version: '3'

services:
  portfolio-web:
    container_name: portfolio-web
    image: portfolio/web
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - caddy_net

networks:
  caddy_net:
    name: caddy_net
    external: true
