services:
    caddy:
        container_name: caddy
        image: caddy
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - caddy_net

volumes:
    caddy_data:
    caddy_config:

networks:
    caddy_net:
        name: caddy_net

