services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9000:9000'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    name: caddy_net
    external: true
